version: '3.8'

services:
  api:
    container_name: "snippet-manager-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment: # Poner estas variables en un archivo .env
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: snippet-manager-db
      DB_HOST: db
      DB_PORT: 5432
    env_file:
      - .env
  db:
    container_name: snippet-manager-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snippet-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
    external: false