FROM openjdk:8-jre-slim
EXPOSE 8080
RUN mkdir /app
COPY ./build/libs/*.jar /app/snippet-manager-service.jar
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=production", "/app/snippet-manager-service.jar"]