version: '3.8'

services:
  api:
    container_name: "snippet-manager-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment: # Poner estas variables en un archivo .env
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: snippet-manager-db
      DB_HOST: db
      DB_PORT: 5432
      DOCKER_PORT: 8080
    env_file:
      - .env
  db:
    container_name: snippet-manager-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: # Poner estas variables en un archivo .env
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snippet-manager-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  asset-service:
    container_name: asset-service-api
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8082:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: false


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite-snippet-manager
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: snippet-manager-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  blob:
  pgdata:
  redisdata: