spring:
  application:
    name: back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:snippet-manager-db}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:admin}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:admin}}
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}

auth0:
  audience: ${AUTH0_AUDIENCE}

server:
  port: 8080